name: Deploy Website

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [dev, self-hosted]

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
