name: Deploy Website

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
